apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: clients-api
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=        
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=    
